backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
media_folder: "assets/images" # Media files will be stored in the repo under assets/images

# Structure for the different content types of the site
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "project{{number}}" # Filename template, e.g., YYYY-MM-DD-title.md TODO: Change the template to something more suitable
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta description", name: "meta", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Link", name: "link", widget: "project{{number}}.md"}
      - {label: "Thumbnail image", name: "thumbnail_image", widget: "image"}
      - {label: "Image 1", name: "project_img_one", widget: "image"}
      - {label: "Image 2", name: "project_img_two", widget: "image"}
      - {label: "Image 3", name: "project_img_three", widget: "image"}

